"use client";
import { RefreshCw, Plus, CalendarDays, Sparkles } from "lucide-react";
import React, { useState, useEffect } from "react";
import axios from "axios";
import { getAccessToken } from "@/libs/axios";
import { MealPlan, AutoGenerateMealPlanDto } from "@/libs/interfaceDTO";
import { mealPlans, userProfiles } from "@/libs/api";
import { useHub } from "@/libs/useHub";
import { toast } from "sonner";
import { DayOfWeek } from "@/libs/enums";
import { MealPlanDayCard } from "../../../components/meal-plans/MealPlanDayCard";
import { MealPlanInsights } from "../../../components/meal-plans/MealPlanInsights";
import { MealPlanSkeleton } from "../../../components/meal-plans/MealPlanSkeleton";
import { AutoGenerateModal } from "../../../components/meal-plans/AutoGenerateModal";
import { useLocalization } from "@/libs/localization";

const days = [
  { label: "Sunday", value: DayOfWeek.Sunday },
  { label: "Monday", value: DayOfWeek.Monday },
  { label: "Tuesday", value: DayOfWeek.Tuesday },
  { label: "Wednesday", value: DayOfWeek.Wednesday },
  { label: "Thursday", value: DayOfWeek.Thursday },
  { label: "Friday", value: DayOfWeek.Friday },
  { label: "Saturday", value: DayOfWeek.Saturday },
];
export default function MealPlansPage() {
  const { L } = useLocalization();
  const [userMealPlans, setUserMealPlans] = useState<MealPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isAutoGenerateModalOpen, setIsAutoGenerateModalOpen] = useState(false);

  const handleAutoGenerate = async (preferences: AutoGenerateMealPlanDto) => {
    try {
      const response = await mealPlans.autoGenerate(preferences);
      setUserMealPlans(response.data);
      toast.success(L("MealPlannerAPI", "MealPlanAutoGeneratedSuccess"));
    } catch (err) {
      if (axios.isAxiosError(err)) {
        console.error(
          "Failed to auto generate:",
          err.response?.data || err.message,
        );
        toast.error(
          err.response?.data?.error?.message ||
            L("MealPlannerAPI", "FailedToAutoGenerateMealPlan"),
        );
      } else {
        console.error("Failed to auto generate:", err);
        toast.error(L("AbpUi", "UnexpectedErrorOccurred"));
      }
    }
  };
  const controller = new AbortController();

  const fetchMealPlans = async () => {
    try {
      setLoading(true);
      setError(null);
      const token = await getAccessToken();
      if (token) {
        const profileResponse = await userProfiles.getMe({
          signal: controller.signal,
        });
        const currentUserId = profileResponse.data.id;

        const mealPlanResponse = await mealPlans.getListByUserId({
          userId: currentUserId,
          maxResultCount: 1,
          skipCount: 0,
        });

        if (
          mealPlanResponse.data.items &&
          mealPlanResponse.data.items.length > 0
        ) {
          setUserMealPlans(mealPlanResponse.data.items[0]);
          console.log("Meal plan fetched:", mealPlanResponse.data.items[0]);
        } else {
          setUserMealPlans(null);
        }
      }
    } catch (err) {
      if (axios.isCancel(err)) return;
      console.error("Error fetching meal plans:", err);
      setError(L("MealPlannerAPI", "FailedToFetchMealPlans"));
      toast.error(L("MealPlannerAPI", "CouldNotLoadMealPlans"));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMealPlans();
    return () => controller.abort();
  }, []);

  const handleDeleteEntry = async (entryId: string) => {
    if (!userMealPlans) return;
    try {
      await mealPlans.removeEntry(entryId, userMealPlans.id);
      setUserMealPlans((prev) => {
        if (!prev?.days) return prev;
        return {
          ...prev,
          days: prev.days.map((day) => ({
            ...day,
            meals: day.meals.filter((m) => m.id !== entryId),
          })),
        };
      });
      toast.success(L("MealPlannerAPI", "MealRemoved"));
    } catch (err) {
      if (axios.isAxiosError(err)) {
        console.error("Delete failed:", err.response?.data ?? err.message);
        toast.error(
          err.response?.data?.error?.message ??
            L("MealPlannerAPI", "FailedToRemoveMeal"),
        );
      } else {
        console.error("Delete failed:", err);
        toast.error(L("AbpUi", "UnexpectedErrorOccurred"));
      }
    }
  };
  useHub({
    onMealPlanUpdated: (updatedPlan: MealPlan) => {
      setUserMealPlans(updatedPlan);
      toast.info(L("MealPlannerAPI", "MealPlanUpdated"));
    },
  });

  const organizeByDay = () => {
    if (!userMealPlans?.days) return {};
    return Object.fromEntries(
      userMealPlans.days.map((day) => [day.dayOfWeek, day.meals]),
    );
  };

  const organizedEntries = organizeByDay();

  return (
    <div className="w-full px-4 sm:px-6 pt-24 pb-16 min-h-screen animate-page-in">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-12 gap-8">
        <div>
          <h1 className="text-5xl font-black text-zinc-900 dark:text-white tracking-tight">
            {L("MealPlannerAPI", "WeeklyMealPlanner")}
          </h1>
          <p className="mt-3 text-lg text-zinc-500 dark:text-zinc-400">
            {L("MealPlannerAPI", "ManageYourCulinaryJourney")}
          </p>
        </div>
        <div className="flex flex-col gap-3">
          <button className="flex items-center justify-center gap-2 bg-emerald-500 hover:bg-emerald-600 text-white px-8 py-4 rounded-2xl font-bold transition-all shadow-xl shadow-emerald-500/20 hover:shadow-emerald-500/40 active:scale-[0.98]">
            <Plus size={24} />
            <span>{L("MealPlannerAPI", "CreateNewPlan")}</span>
          </button>
          <button
            onClick={() => setIsAutoGenerateModalOpen(true)}
            className="flex items-center justify-center gap-2 bg-indigo-500 hover:bg-indigo-600
             text-white px-8 py-4 rounded-2xl font-bold transition-all shadow-xl
              shadow-indigo-500/20 hover:shadow-indigo-500/40 active:scale-[0.98]"
          >
            <Sparkles size={24} />
            <span>{L("MealPlannerAPI", "AutoGeneratePlan")}</span>
          </button>
        </div>
      </div>

      <div className="relative">
        <div className="absolute top-0 right-0 -mr-40 -mt-40 w-96 h-96 bg-emerald-500/5 rounded-full blur-[120px] pointer-events-none" />
        <div className="absolute bottom-0 left-0 -ml-40 -mb-40 w-96 h-96 bg-blue-500/5 rounded-full blur-[120px] pointer-events-none" />

        <div className="relative z-10">
          <div className="flex items-center justify-between mb-10">
            <h2 className="text-3xl font-extrabold text-zinc-900 dark:text-white flex items-center gap-3">
              <CalendarDays className="text-emerald-500" size={32} />
              <span>{L("MealPlannerAPI", "CurrentSchedule")}</span>
            </h2>
            <button
              onClick={fetchMealPlans}
              disabled={loading}
              className="p-4 text-zinc-500 hover:text-emerald-500 transition-all rounded-2xl bg-zinc-100/50 dark:bg-zinc-800/50 hover:bg-emerald-50 dark:hover:bg-emerald-500/10 disabled:opacity-50 border border-zinc-200/50 dark:border-zinc-700/50"
            >
              <RefreshCw
                size={22}
                className={loading && userMealPlans ? "animate-spin" : ""}
              />
            </button>
          </div>

          <div className="space-y-12">
            {loading ? (
              <MealPlanSkeleton />
            ) : error ? (
              <div className="flex flex-col items-center justify-center py-24 bg-zinc-50/50 dark:bg-zinc-800/20 rounded-[2.5rem] border border-red-100 dark:border-red-900/10">
                <p className="text-red-500 font-bold mb-8 text-xl">{error}</p>
                <button
                  onClick={fetchMealPlans}
                  className="px-10 py-4 bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900 rounded-2xl font-bold hover:opacity-90 transition-all shadow-lg"
                >
                  {L("AbpUi", "Retry")}
                </button>
              </div>
            ) : (
              <div className="bg-transparent border-none">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-7 gap-4 xl:gap-6">
                  {days.map((dayName) => (
                    <MealPlanDayCard
                      key={dayName.value}
                      dayName={dayName.label}
                      dayIndex={dayName.value}
                      mealPlanId={userMealPlans?.id ?? ""}
                      dayEntries={organizedEntries[dayName.value] ?? []}
                      onDeleteEntry={handleDeleteEntry}
                    />
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="space-y-12">
            <MealPlanInsights userMealPlans={userMealPlans} />
          </div>
        </div>
      </div>

      <AutoGenerateModal
        isOpen={isAutoGenerateModalOpen}
        onClose={() => setIsAutoGenerateModalOpen(false)}
        onGenerate={handleAutoGenerate}
      />
    </div>
  );
}
