"use client";
import { RefreshCw, Plus, CalendarDays, Sparkles } from "lucide-react";
import React, { useState, useEffect } from "react";
import axios from "axios";
import { getAccessToken } from "@/libs/axios";
import { MealPlan, AutoGenerateMealPlanDto } from "@/libs/interfaceDTO";
import { mealPlans, userProfiles } from "@/libs/api";
import { useHub } from "@/hooks/useHub";
import { toast } from "sonner";
import { DayOfWeek } from "@/libs/enums";
import { MealPlanDayCard } from "../../../components/meal-plans/MealPlanDayCard";
import { MealPlanInsights } from "../../../components/meal-plans/MealPlanInsights";
import { MealPlanSkeleton } from "../../../components/meal-plans/MealPlanSkeleton";
import { AutoGenerateModal } from "../../../components/meal-plans/AutoGenerateModal";
import { useLocalization } from "@/libs/LocalizationProvider";
import { AppPageHeader } from "@/components/layout/AppPageHeader";
import { AppSection } from "@/components/layout/AppSection";

const days = [
  { labelKey: "MealPlan:Sunday", value: DayOfWeek.Sunday },
  { labelKey: "MealPlan:Monday", value: DayOfWeek.Monday },
  { labelKey: "MealPlan:Tuesday", value: DayOfWeek.Tuesday },
  { labelKey: "MealPlan:Wednesday", value: DayOfWeek.Wednesday },
  { labelKey: "MealPlan:Thursday", value: DayOfWeek.Thursday },
  { labelKey: "MealPlan:Friday", value: DayOfWeek.Friday },
  { labelKey: "MealPlan:Saturday", value: DayOfWeek.Saturday },
];
export default function MealPlansPage() {
  const { L } = useLocalization();
  const [userMealPlans, setUserMealPlans] = useState<MealPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isAutoGenerateModalOpen, setIsAutoGenerateModalOpen] = useState(false);

  const handleAutoGenerate = async (preferences: AutoGenerateMealPlanDto) => {
    try {
      const response = await mealPlans.autoGenerate(preferences);
      setUserMealPlans(response.data);
      toast.success(L("MealPlannerAPI", "MealPlan:AutoGeneratedSuccess"));
    } catch (err) {
      if (axios.isAxiosError(err)) {
        console.error(
          "Failed to auto generate:",
          err.response?.data || err.message,
        );
        toast.error(
          err.response?.data?.error?.message ||
            L("MealPlannerAPI", "MealPlan:AutoGeneratedFailed"),
        );
      } else {
        console.error("Failed to auto generate:", err);
        toast.error(L("MealPlannerAPI", "Common:UnexpectedErrorOccurred"));
      }
    }
  };
  const controller = new AbortController();

  const fetchMealPlans = async () => {
    try {
      setLoading(true);
      setError(null);
      const token = await getAccessToken();
      if (token) {
        const profileResponse = await userProfiles.getMe({
          signal: controller.signal,
        });
        const currentUserId = profileResponse.data.id;

        const mealPlanResponse = await mealPlans.getListByUserId({
          userId: currentUserId,
          maxResultCount: 1,
          skipCount: 0,
        });

        if (
          mealPlanResponse.data.items &&
          mealPlanResponse.data.items.length > 0
        ) {
          setUserMealPlans(mealPlanResponse.data.items[0]);
          console.log("Meal plan fetched:", mealPlanResponse.data.items[0]);
        } else {
          setUserMealPlans(null);
        }
      }
    } catch (err) {
      if (axios.isCancel(err)) return;
      console.error("Error fetching meal plans:", err);
      setError(L("MealPlannerAPI", "MealPlan:FailedToFetch"));
      toast.error(L("MealPlannerAPI", "MealPlan:LoadFailed"));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMealPlans();
    return () => controller.abort();
  }, []);

  const handleDeleteEntry = async (entryId: string) => {
    if (!userMealPlans) return;
    try {
      await mealPlans.removeEntry(entryId, userMealPlans.id);
      setUserMealPlans((prev) => {
        if (!prev?.days) return prev;
        return {
          ...prev,
          days: prev.days.map((day) => ({
            ...day,
            meals: day.meals.filter((m) => m.id !== entryId),
          })),
        };
      });
      toast.success(L("MealPlannerAPI", "MealPlan:MealRemoved"));
    } catch (err) {
      if (axios.isAxiosError(err)) {
        console.error("Delete failed:", err.response?.data ?? err.message);
        toast.error(
          err.response?.data?.error?.message ??
            L("MealPlannerAPI", "MealPlan:RemoveFailed"),
        );
      } else {
        console.error("Delete failed:", err);
        toast.error(L("MealPlannerAPI", "Common:UnexpectedErrorOccurred"));
      }
    }
  };
  useHub({
    onMealPlanUpdated: (updatedPlan: MealPlan) => {
      setUserMealPlans(updatedPlan);
      toast.info(L("MealPlannerAPI", "MealPlan:Updated"));
    },
  });

  const organizeByDay = () => {
    if (!userMealPlans?.days) return {};
    return Object.fromEntries(
      userMealPlans.days.map((day) => [day.dayOfWeek, day.meals]),
    );
  };

  const organizedEntries = organizeByDay();

  return (
    <div className="w-full px-4 sm:px-6 pt-24 pb-16 min-h-screen animate-page-in">
      <AppPageHeader
        className="mb-10"
        gradientClassName="bg-primary-secondary-315"
        icon={CalendarDays}
        title={L("MealPlannerAPI", "MealPlan:Title")}
        description={L("MealPlannerAPI", "MealPlan:Description")}
        contentClassName="md:flex-row md:items-center gap-6"
        actions={
          <div className="flex flex-col sm:flex-row gap-3">
            <button className="flex items-center justify-center gap-2 bg-brand-gradient text-white px-6 py-3 rounded-xl font-semibold transition-all shadow-brand-glow-sm hover:shadow-brand-glow active:scale-[0.98]">
              <Plus size={20} aria-hidden="true" />
              <span>{L("MealPlannerAPI", "MealPlan:CreateNew")}</span>
            </button>
            <button
              onClick={() => setIsAutoGenerateModalOpen(true)}
              className="flex items-center justify-center gap-2 bg-primary-secondary-225 border border-primary/20 text-foreground px-6 py-3 rounded-xl font-semibold transition-all hover:shadow-brand-glow-sm active:scale-[0.98]"
            >
              <Sparkles size={20} aria-hidden="true" />
              <span>{L("MealPlannerAPI", "MealPlan:AutoGenerate")}</span>
            </button>
          </div>
        }
      />

      <div className="relative">
        {/* Ambient blobs using brand gradient colors */}
        <div className="absolute top-0 right-0 -mr-40 -mt-40 w-96 h-96 rounded-full blur-[120px] pointer-events-none bg-primary-secondary-90 opacity-30" />
        <div className="absolute bottom-0 left-0 -ml-40 -mb-40 w-96 h-96 rounded-full blur-[120px] pointer-events-none bg-primary-secondary-270 opacity-30" />

        <div className="relative z-10">
          <AppSection
            title={L("MealPlannerAPI", "MealPlan:CurrentSchedule")}
            icon={CalendarDays}
            action={
              <button
                onClick={fetchMealPlans}
                className="p-3 text-muted-foreground hover:text-primary transition-all rounded-xl bg-muted/50 hover:bg-primary/10 disabled:opacity-50 border border-border"
              >
                <RefreshCw
                  size={20}
                  className={loading && userMealPlans ? "animate-spin" : ""}
                  aria-hidden="true"
                />
              </button>
            }
          >
            {loading ? (
              <MealPlanSkeleton />
            ) : error ? (
              <div className="flex flex-col items-center justify-center py-24 bg-primary-secondary-radial rounded-3xl border border-destructive/20">
                <p className="text-destructive font-bold mb-8 text-xl">
                  {error}
                </p>
                <button
                  onClick={fetchMealPlans}
                  className="px-8 py-3 bg-brand-gradient text-white rounded-xl font-semibold hover:opacity-90 transition-all shadow-brand-glow-sm"
                >
                  {L("MealPlannerAPI", "Common:Retry")}
                </button>
              </div>
            ) : (
              <div className="bg-transparent border-none">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-7 gap-4 xl:gap-6">
                  {days.map((dayName) => (
                    <MealPlanDayCard
                      key={dayName.value}
                      dayName={L("MealPlannerAPI", dayName.labelKey)}
                      dayIndex={dayName.value}
                      mealPlanId={userMealPlans?.id ?? ""}
                      dayEntries={organizedEntries[dayName.value] ?? []}
                      onDeleteEntry={handleDeleteEntry}
                    />
                  ))}
                </div>
              </div>
            )}
          </AppSection>

          <div className="space-y-12">
            <MealPlanInsights userMealPlans={userMealPlans} />
          </div>
        </div>
      </div>

      <AutoGenerateModal
        isOpen={isAutoGenerateModalOpen}
        onClose={() => setIsAutoGenerateModalOpen(false)}
        onGenerate={handleAutoGenerate}
      />
    </div>
  );
}
